//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMR_Curriculum_Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_map
    {
        public int CompanyMapID { get; set; }
        public int CompanyID { get; set; }
        public int ContentID { get; set; }
    
        public virtual content content { get; set; }
        public virtual company_list company_list { get; set; }
    }
}
