//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMR_Curriculum_Database.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trm_cmridev16Entities : DbContext
    {
        public trm_cmridev16Entities()
            : base("name=trm_cmridev16Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cmri_mip16_offerings> cmri_mip16_offerings { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<company_map> company_maps { get; set; }
    }
}
