//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMR_Curriculum_Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parent_course_map
    {
        public int ID { get; set; }
        public int Parent_Course_ID { get; set; }
        public int Module_ID { get; set; }
    
        public virtual content content { get; set; }
        public virtual parent_course parent_course { get; set; }
    }
}
